emojis:
  grinning: ยงe๐ยงr
  smiley: ยงe๐ยงr
  smile: ยงe๐ยงr
  grin: ยงe๐ยงr
  laughing: ยงe๐ยงr
  sweat_smile: ยงe๐ยงr
  rofl: ยงe๐คฃยงr
  joy: ยงe๐ยงr
  slightly_smiling_face: ยงe๐ยงr
  upside_down_face: ยงe๐ยงr
  wink: ยงe๐ยงr
  blush: ยงe๐ยงr
  innocent: ยงe๐ยงr
  heart_eyes: ยงe๐ยงr
  kissing_heart: ยงe๐ยงr
  kissing: ยงe๐ยงr
  kissing_closed_eyes: ยงe๐ยงr
  kissing_smiling_eyes: ยงe๐ยงr
  yum: ยงe๐ยงr
  stuck_out_tongue: ยงe๐ยงr
  stuck_out_tongue_winking_eye: ยงe๐ยงr
  stuck_out_tongue_closed_eyes: ยงe๐ยงr
  sunglasses: ยงe๐ยงr
  smirk: ยงe๐ยงr
  neutral_face: ยงe๐ยงr
  expressionless: ยงe๐ยงr
  unamused: ยงe๐ยงr
  sweat: ยงe๐ยงr
  pensive: ยงe๐ยงr
  confused: ยงe๐ยงr
  confounded: ยงe๐ยงr
  rage: ยง4๐กยงr
  angry: ยงe๐ยงr
  cry: ยงe๐ขยงr
  persevere: ยงe๐ฃยงr
  triumph: ยงe๐คยงr
  disappointed_relieved: ยงe๐ฅยงr
  frowning: ยงe๐ฆยงr
  anguished: ยงe๐งยงr
  fearful: ยงe๐จยงr
  weary: ยงe๐ฉยงr
  sleepy: ยงe๐ชยงr
  tired_face: ยงe๐ซยงr
  sob: ยงe๐ญยงr
  cold_sweat: ยงe๐ฐยงr
  scream: ยงe๐ฑยงr
  flushed: ยงe๐ณยงr
  dizzy_face: ยงe๐ตยงr
  exploding_head: ยงe๐คฏยงr
  face_with_symbols_over_mouth: ยง4๐คฌยงr
  cowboy: ยงe๐คยงr
  clown: ยงc๐คกยงr
  poop: ยง6๐ฉยงr
  ghost: ยง8๐ปยงr
  skull: ๐
  robot: ๐ค
  heart: ยงcโค๏ธยงr
  yellow_heart: ยงe๐ยงr
  green_heart: ยงa๐ยงr
  blue_heart: ยง1๐ยงr
  purple_heart: ยง5๐ยงr
  black_heart: ยง0๐คยงr
  broken_heart: ยงc๐ยงr
  two_hearts: ยงc๐ยงr
  sparkling_heart: ยงc๐ยงr
  heartbeat: ยงc๐ยงr
  fire: ยงe๐ฅยงr
  '100': ยงc๐ฏยงr
  thumbsup: ยงe๐ยงr
  thumbsdown: ยงe๐ยงr
  ok_hand: ยงe๐ยงr
  clap: ยงe๐ยงr
  pray: ยงe๐ยงr
  muscle: ยงe๐ชยงr
  eyes: ๐
  raised_hands: ยงe๐ยงr
  facepalm: ยงe๐คฆยงr
  shrug: ยงe๐คทยงr
  v: ยงeโยงe
  wave: ยงe๐ยงr
  call_me: ยงe๐คยงr
  metal: ยงe๐คยงr
  writing_hand: ยงeโ๏ธยงr
  dog: ๐ถ
  cat: ยงe๐ฑยงr
  mouse: ๐ญ
  hamster: ๐น
  rabbit: ๐ฐ
  fox_face: ๐ฆ
  bear: ๐ป
  panda_face: ๐ผ
  koala: ๐จ
  tiger: ๐ฏ
  lion: ๐ฆ
  cow: ๐ฎ
  pig: ๐ท
  frog: ๐ธ
  monkey_face: ๐ต
  chicken: ๐
  penguin: ๐ง
  bird: ๐ฆ
  baby_chick: ๐ค
  pizza: ยงe๐ยงr
  hamburger: ๐
  fries: ๐
  hotdog: ๐ญ
  taco: ๐ฎ
  burrito: ๐ฏ
  ramen: ๐
  spaghetti: ๐
  sushi: ๐ฃ
  cake: ๐ฐ
  cupcake: ๐ง
  ice_cream: ๐จ
  chocolate_bar: ๐ซ
  popcorn: ๐ฟ
  coffee: โ
  tea: ๐ต
  beer: ๐บ
  wine_glass: ๐ท
  cocktail: ๐ธ
  soccer: โฝ
  basketball: ยงe๐ยงr
  football: ยง6๐ยงr
  baseball: โพ
  tennis: ๐พ
  trophy: ยงe๐ยงr
